import json
from pathlib import Path

REPO_DIR = Path("repo")

# Load the raw data generated by Inspector.jar
with REPO_DIR.joinpath("output.json").open("r", encoding="utf-8") as f:
    inspector_data = json.load(f)

# Preserve all V2 metadata and ensure types and paths are correct
for ext in inspector_data:
    # Ensure the APK path has the correct folder prefix
    if "apk" in ext and not ext["apk"].startswith("apk/"):
        ext["apk"] = f"apk/{ext['apk']}"
        
    # Ensure ID is a pure integer so Animetail doesn't crash
    if "sources" in ext:
        for source in ext["sources"]:
            if "id" in source:
                source["id"] = int(source["id"])

# Save the pristine list ready for merging
with REPO_DIR.joinpath("index.min.json").open("w", encoding="utf-8") as f:
    json.dump(inspector_data, f, ensure_ascii=False, separators=(",", ":"))
